--- a/app/layout.tsx
+++ b/app/layout.tsx
@@
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
+// No config needed; the package ships the font files.

export const metadata: Metadata = {
  title: "Create Next App",
 };
 
 export default function RootLayout({
   children,
  description: "Generated by create next app",
   children: React.ReactNode;
 }) {
   return (
     <html lang="en">
-      <body className={`${geist.className} ${geistMono.className}`}>
+      <body className={`${GeistSans.className} ${GeistMono.className}`}>
};
       </body>
     </html>
   );
 }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
